version: "4.14.1"

services:
    nodered:
        build: s-node-red
        #image: nodered/node-red
        ports:
            - "5000:1880"

    mosquitto:
        image: eclipse-mosquitto
        ports:
          - "5001:1883"
          - "9001:9001"
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log

    python-server:
        build: pythonServer
        #image: python
        depends_on:
            - mosquitto
        volumes:
            - ./pythonServer:/pythonServer

       
    
       

    
   
    
    